# Generated by Django 3.0.3 on 2020-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='countries_covid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.CharField(choices=[('K', 'Korea, South'), ('C', 'China'), ('UK', 'United Kingdom'), ('US', 'US'), ('F', 'France')], max_length=100)),
                ('confirmed', models.FloatField()),
                ('recovered', models.FloatField()),
                ('deaths', models.FloatField()),
            ],
        ),
    ]
